### ISSUE TITLE
Orientation / Rotation EXIF metadata seemingly not used

### ISSUE THREAD

**Issue by jakemauer** [MikeGawi/ePiframe#62]
Hi Mike!

First let me say THANK YOU for writing and maintaining a photo frame app that actually works on first install and has a decent webUI. 

I have the ePiframe running on a pi4 b and I'm trying it out using some photos that I copied directly to an album folder in the photos folder in the ePiframe directory on the pi. The images show up! However for vertically shot photos that have EXIF orientations of say 6 (rotated 90º counterclockwise), they display un-rotated on my screen. 

So this image: 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/361568/164322186-79b2dd52-0ca2-4898-946e-d43cbd081174.png">

Renders like this on my photo frame's display:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/361568/164322252-332762c7-620c-4bed-966e-e698b3751aa0.png">

Obviously I can fix the EXIF data, but I would love to be able to drag and drop photos into that folder without preprocessing. Is there an obvious setting or fix that I'm missing?

Thank you again!

**Comment by MikeGawi** [comment]
Thanks for bringing that up! To be honest, I've completely forgot about this information stored in EXIF data and it seems obvious and reasonable to use it as a rotation value for photos (maybe as an option in settings to use EXIF or fixed rotation). I will implement that, especially when ImageMagick used by this project has a possibility to easily extract the data. Thanks!

> First let me say THANK YOU for writing and maintaining a photo frame app that actually works on first install and has a decent webUI.

Thank YOU for the kind words, that really means a lot for me and keeps me going.

**Comment by MikeGawi** [comment]
All examples of EXIF orientations can be found [here](https://github.com/recurser/exif-orientation-examples).
The data can be extracted by ImageMagick with [this solution](https://stackoverflow.com/questions/26654709/extract-exif-data-as-text-using-imagemagick).

**Comment by MikeGawi** [comment]
Done. 
Few remarks:

-  ImageMagick will automatically orientate photo according to EXIF data
- `Auto-orient` takes time, so due to compatibility with Pi Zero option is disabled by default in the configuration (enable by setting `auto_orientation=1` in _config.cfg_ or enable _Auto Orientation_ in UI _Settings->Image_)
- `Auto-orient` takes time even if EXIF information is missing (!), so a small optimization was added, i.e. the code checks for EXIF first before executing `Auto-orient`

Please check this solution and leave a feedback or reopen the issue. 
Cheers!

**Comment by jakemauer** [comment]
WOW Mike!! This was so fast. Thank you!
